color: sky
fieldLayouts:
  eb9f2578-a86f-4cce-bcbf-7d093e23c845:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-08-14T12:35:32+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 5cc3725c-b8d7-4878-9a3d-d12259776771
            userCondition: null
            warning: null
            width: 100
        name: Contenu
        uid: 1e05d3bd-5846-478a-9411-39976ee62917
        userCondition: null
handle: blogPage
hasTitleField: true
icon: rss
name: 'Blog page'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
