color: null
fieldLayouts:
  e844767d-c385-423a-8888-dde51d1853ec:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-08-15T12:17:49+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: f6def800-7e0a-49f7-bcd8-52447e4f4e19
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-15T12:19:22+00:00'
            elementCondition: null
            fieldUid: 79346af6-2fe8-424b-a33b-3a821ea15e58 # Text
            handle: null
            includeInCards: true
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0ba5954a-3ffc-4fd8-98b2-cc6ef8200444
            userCondition: null
            warning: null
            width: 100
        name: Contenu
        uid: 48390ddb-c162-4953-8cb2-bfb98dec0480
        userCondition: null
handle: heading
hasTitleField: false
icon: flag-pennant
name: Heading
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
