color: null
fieldLayouts:
  cc84b24f-244a-451c-86bf-0718173a27fe:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-08-12T08:18:10+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: bb0c6335-79d7-4f4a-9a5b-b8c70059c417
            userCondition: null
            warning: null
            width: 100
        name: Contenu
        uid: 54d9fbf2-b825-46c2-bfd0-ad92ec95af1a
        userCondition: null
handle: portfolio
hasTitleField: true
icon: ''
name: Portfolio
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
