color: null
fieldLayouts:
  cc84b24f-244a-451c-86bf-0718173a27fe:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-08-12T08:18:10+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: bb0c6335-79d7-4f4a-9a5b-b8c70059c417
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-13T11:50:50+00:00'
            elementCondition: null
            fieldUid: 5cee9b0f-499a-453d-959b-64ec559484cc # Image unique
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8d07cc85-381b-4a4a-819e-149403e24006
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-13T11:50:50+00:00'
            elementCondition: null
            fieldUid: 79346af6-2fe8-424b-a33b-3a821ea15e58 # Texte
            handle: projectTitle
            includeInCards: false
            instructions: null
            label: 'Titre du projet'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6ca84150-f12a-4112-8db2-ff5eee6512f5
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-13T11:50:50+00:00'
            elementCondition: null
            fieldUid: 79346af6-2fe8-424b-a33b-3a821ea15e58 # Texte
            handle: subText
            includeInCards: false
            instructions: null
            label: 'Sous texte'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8d9bbe4b-0a4a-4b8a-9188-711db436bec1
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-13T11:55:38+00:00'
            elementCondition: null
            fieldUid: 588e3523-dd00-4fc5-8e05-772f8e351b8f # Domaine d'activité
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 46764e58-1310-4587-96f6-076875c960fb
            userCondition: null
            warning: null
            width: 100
        name: Contenu
        uid: 54d9fbf2-b825-46c2-bfd0-ad92ec95af1a
        userCondition: null
handle: portfolio
hasTitleField: true
icon: ''
name: Portfolio
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
