color: yellow
fieldLayouts:
  cc84b24f-244a-451c-86bf-0718173a27fe:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-08-12T08:18:10+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: bb0c6335-79d7-4f4a-9a5b-b8c70059c417
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-13T11:50:50+00:00'
            elementCondition: null
            fieldUid: 5cee9b0f-499a-453d-959b-64ec559484cc # Image unique
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8d07cc85-381b-4a4a-819e-149403e24006
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-13T11:50:50+00:00'
            elementCondition: null
            fieldUid: 79346af6-2fe8-424b-a33b-3a821ea15e58 # Text
            handle: projectTitle
            includeInCards: false
            instructions: null
            label: 'Titre du projet'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6ca84150-f12a-4112-8db2-ff5eee6512f5
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-13T11:50:50+00:00'
            elementCondition: null
            fieldUid: 79346af6-2fe8-424b-a33b-3a821ea15e58 # Text
            handle: subText
            includeInCards: false
            instructions: null
            label: 'Sous texte'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8d9bbe4b-0a4a-4b8a-9188-711db436bec1
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-13T11:55:38+00:00'
            elementCondition: null
            fieldUid: 588e3523-dd00-4fc5-8e05-772f8e351b8f # Domaine d'activité
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 46764e58-1310-4587-96f6-076875c960fb
            userCondition: null
            warning: null
            width: 100
        name: 'Homepage content'
        uid: 54d9fbf2-b825-46c2-bfd0-ad92ec95af1a
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-08-16T11:33:35+00:00'
            elementCondition: null
            fieldUid: 81d01265-3359-4e47-ba43-a13fa83ee2a0 # Multiple images
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1c9283bc-c025-4e4b-a4e4-6c15d1323212
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-16T11:45:41+00:00'
            elementCondition: null
            fieldUid: 79346af6-2fe8-424b-a33b-3a821ea15e58 # Text
            handle: infoTableTitle
            includeInCards: false
            instructions: null
            label: 'Titre du tableau d''information'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4a6e3b6a-27b1-4e90-b815-e9a5658aa3ab
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-16T11:33:35+00:00'
            elementCondition: null
            fieldUid: eef85724-4842-4dcf-8997-e217b4129df6 # Tableau d'information
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c3737f8b-0443-4547-959c-88125652b501
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-16T11:33:35+00:00'
            elementCondition: null
            fieldUid: 79346af6-2fe8-424b-a33b-3a821ea15e58 # Text
            handle: descriptionTitle
            includeInCards: false
            instructions: null
            label: 'Titre de description'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 86a0a6d8-6769-49bc-85fd-887887af3c2e
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-16T11:33:35+00:00'
            elementCondition: null
            fieldUid: 4c1cf3ab-0da9-4467-b2a2-cd40fa72151b # Texte riche
            handle: descriptionText
            includeInCards: false
            instructions: null
            label: 'Paragraphe de description'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fcbf57c8-e63f-463d-b728-f7f28d47b5be
            userCondition: null
            warning: null
            width: 100
        name: 'Project content'
        uid: b8ff0fa5-25b3-4333-9fae-8c1698746baa
        userCondition: null
handle: portfolioProjects
hasTitleField: true
icon: address-card
name: 'Portfolio projects'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
