color: amber
fieldLayouts:
  af457518-8542-46b7-b621-3977d00bf014:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-08-14T12:34:20+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 79e0156e-c31d-49f9-a7dc-5c55642d7f40
            userCondition: null
            warning: null
            width: 100
        name: Contenu
        uid: 8250a429-25e4-4c78-ad4a-9aebb8b9202e
        userCondition: null
handle: portfolioPage
hasTitleField: true
icon: address-book
name: 'Portfolio page'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
