color: null
fieldLayouts:
  8ec7eafd-ccde-4b68-81ca-2a96e20780b6:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-08-15T12:08:17+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: ceb40d57-02bd-4eda-a16e-0c1f8d10a694
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-15T12:11:38+00:00'
            elementCondition: null
            fieldUid: 4c1cf3ab-0da9-4467-b2a2-cd40fa72151b # Texte riche
            handle: null
            includeInCards: true
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a18f0495-b98b-4d0a-b586-dd963888f9c7
            userCondition: null
            warning: null
            width: 100
        name: Contenu
        uid: addf6150-699c-4265-9efd-92d7c34a27e9
        userCondition: null
handle: richText
hasTitleField: false
icon: paragraph
name: 'Texte riche'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
