defaultPlacement: end
fieldLayouts:
  abbcaa8d-2d19-4d95-97e0-8fbb9f4c2a8e:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-08-13T11:42:57+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            uid: 016693f8-5f7a-40c6-b113-d7b227938b48
            userCondition: null
            warning: null
            width: 100
        name: Contenu
        uid: 6cfbe221-0200-48e6-8349-72fffc9ec856
        userCondition: null
handle: activity
name: 'Domaine d''activité'
siteSettings:
  72d57a2e-efaa-45e8-8aa0-abee06f37785: # Lafitte's Original
    hasUrls: true
    template: activity/_category.twig
    uriFormat: 'activites/{slug}'
structure:
  maxLevels: null
  uid: e1ca084f-6bbe-40e7-afda-af7e73866f8e
