columnSuffix: null
handle: address
instructions: null
name: Adresse
searchable: false
settings:
  maxAddresses: null
  minAddresses: null
  viewMode: cards
translationKeyFormat: null
translationMethod: site
type: craft\fields\Addresses
