columnSuffix: null
handle: richText
instructions: null
name: 'Texte riche'
searchable: false
settings:
  availableTransforms: ''
  availableVolumes: '*'
  ckeConfig: 444c4fac-c573-4adc-984d-3c1671b9fabe # Simple
  createButtonLabel: null
  defaultTransform: null
  enableSourceEditingForNonAdmins: true
  purifierConfig: null
  purifyHtml: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  showWordCount: false
  wordLimit: null
translationKeyFormat: null
translationMethod: none
type: craft\ckeditor\Field
