columnSuffix: null
handle: text
instructions: null
name: Texte
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  initialRows: 4
  multiline: false
  placeholder: Test
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
