dateModified: 1723726304
email:
  fromEmail: $CONTACT_EMAIL
  fromName: 'Lafitte''s Original'
  replyToEmail: $CONTACT_EMAIL
  template: null
  transportSettings:
    command: '/usr/local/bin/mailpit sendmail -t --smtp-addr 127.0.0.1:1025'
  transportType: craft\mail\transportadapters\Sendmail
fs:
  images:
    hasUrls: true
    name: Images
    settings:
      path: '@assetBasePath/images'
    type: craft\fs\Local
    url: '@assetBaseUrl/images'
meta:
  __names__:
    0c37905a-d5f4-4816-a946-a6b9a808e742: 'Content block' # Content block
    002a10e3-729c-4284-8ec2-920871a6001d: 'Public Schema' # Public Schema
    2d76a4ed-1de2-4561-ab8e-dfcdfab066c4: 'Blog articles' # Blog articles
    3d2f8f39-b4c4-4889-883b-1a16314464be: Email # Email
    003e7855-a801-43fa-8c0c-da3f8bead280: 'Réseaux sociaux' # Réseaux sociaux
    4c1cf3ab-0da9-4467-b2a2-cd40fa72151b: 'Texte riche' # Texte riche
    5cee9b0f-499a-453d-959b-64ec559484cc: 'Image unique' # Image unique
    6cf4390c-e895-47ec-a321-feba1e1e7501: 'Liste avec icônes' # Liste avec icônes
    8f67eb5a-6e04-42fb-8334-a906b8222a9e: Navigation # Navigation
    9acad094-6e07-4bb0-819f-9c7fec768f2a: Home # Home
    28bd6954-2b69-4848-85bc-d5f924f0481f: 'Portfolio projects' # Portfolio projects
    43da522b-bfe0-40f1-8162-084e48fda1ab: Contact # Contact
    48fe682e-c0f9-488a-aef6-f57bf914d5ef: Home # Home
    49f7b880-8350-4e7e-bd17-cbe0d427732c: About # About
    52b05483-7e0d-490a-ad33-b26095e93fd9: Adresse # Adresse
    72d57a2e-efaa-45e8-8aa0-abee06f37785: 'Lafitte''s Original' # Lafitte's Original
    221b61f5-0f46-4d9f-a0d3-14441bbf3588: Images # Images
    350dc498-f98e-41be-869a-4d00dc55af15: 'Texte riche' # Texte riche
    397d15f9-4743-40b6-b08e-f55dec5d0c13: 'Blog articles' # Blog articles
    407a59c6-071c-4759-8d4c-9cab338f8906: Contact # Contact
    444c4fac-c573-4adc-984d-3c1671b9fabe: Simple # Simple
    588e3523-dd00-4fc5-8e05-772f8e351b8f: 'Domaine d''activité' # Domaine d'activité
    616d0d46-23c9-496d-827f-ef771cbd2b71: Header # Header
    849c5f71-cf05-49f8-b038-aeeb5d1a696a: 'Blog page' # Blog page
    1468bf93-b003-407b-b3eb-74bd76867ce7: 'Portfolio projects' # Portfolio projects
    79346af6-2fe8-424b-a33b-3a821ea15e58: Texte # Texte
    56497856-37c4-4c09-967f-a22cb2aafafe: 'Lafitte''s Original' # Lafitte's Original
    64967050-1f66-485f-83a7-672e01130188: Blog # Blog
    a8949d68-f029-4477-a5eb-31d7feeb2692: Heading # Heading
    ad838d51-70b0-46e8-b8b8-b45d13bf9290: 'Portfolio ' # Portfolio 
    eac18b4f-6a99-44b0-8452-4678a0badd91: 'Domaine d''activité' # Domaine d'activité
    fa5b2b7b-9166-43f6-8ebd-b5b9483c0d13: Footer # Footer
    ff5abc68-4f33-4a98-b08b-4d27f4027ccb: 'Portfolio page' # Portfolio page
plugins:
  ckeditor:
    edition: standard
    enabled: true
    schemaVersion: 3.0.0.0
  contact-form:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
    settings:
      allowAttachments: ''
      allowedMessageFields: null
      prependSender: 'De la part de'
      prependSubject: 'Nouveau message de Lafitte''s Original'
      successFlashMessage: 'Votre message a bien été envoyé.'
      toEmail: clairelafitte37@gmail.com
  contact-form-extensions:
    edition: standard
    enabled: true
    schemaVersion: 1.0.1
    settings:
      confirmationSubject: ''
      confirmationTemplate: ''
      enableConfirmationEmail: ''
      enableDatabase: '1'
      enableRecaptchaOverride: ''
      enableTemplateOverwrite: ''
      notificationTemplate: ''
      recaptcha: ''
      recaptchaDataBadge: bottomright
      recaptchaDebug: ''
      recaptchaHideBadge: ''
      recaptchaSecretKey: ''
      recaptchaSiteKey: ''
      recaptchaThreshold: '0.5'
      recaptchaTimeout: '5'
      recaptchaUrl: ''
      recaptchaVerificationUrl: ''
      recaptchaVersion: ''
  stripe:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
system:
  edition: solo
  live: true
  name: 'Lafitte''s Original'
  retryDuration: null
  schemaVersion: 5.3.0.2
  timeZone: Europe/Paris
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  require2fa: false
  requireEmailVerification: true
