fieldLayouts:
  d3bf29b1-c9d0-4042-a1cc-491588cbfa06:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-11-05T10:07:03+00:00'
            elementCondition: null
            fieldUid: 003e7855-a801-43fa-8c0c-da3f8bead280 # Réseaux sociaux
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 517a2af2-eeaa-498c-9c25-99551817a42d
            userCondition: null
            warning: null
            width: 100
        name: Contenu
        uid: 507226c3-32b1-4522-9b5e-c007d65f772f
        userCondition: null
handle: general
name: Général
sortOrder: 4
