defaultPlacement: end
enableVersioning: true
entryTypes:
  - 397d15f9-4743-40b6-b08e-f55dec5d0c13 # Blog articles
handle: blog
maxAuthors: 1
name: 'Blog articles'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Page d‘entrée primaire'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  72d57a2e-efaa-45e8-8aa0-abee06f37785: # Lafitte's Original
    enabledByDefault: true
    hasUrls: true
    template: pages/blog/_article.twig
    uriFormat: 'blog/{slug}'
type: channel
