defaultPlacement: end
enableVersioning: true
entryTypes:
  - ff5abc68-4f33-4a98-b08b-4d27f4027ccb # Portfolio page
handle: portfolioPage
maxAuthors: 1
name: 'Portfolio '
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Page d‘entrée primaire'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  72d57a2e-efaa-45e8-8aa0-abee06f37785: # Lafitte's Original
    enabledByDefault: true
    hasUrls: true
    template: null
    uriFormat: '#portfolio'
type: single
